name: Deploy React App to S3

on:
  push:
    branches:
      - main  # Workflow berjalan jika ada push ke branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Mengambil kode dari repositori

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # Versi Node.js untuk build React

      - name: Install dependencies and build React app
        run: |
          npm install
          npm run build  # Generate folder 'build/'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Versi Python

      - name: Install dependencies for Python
        run: |
          python -m pip install --upgrade pip
          pip install boto3 python-dotenv

      - name: Create .env file
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_KEY }}" >> .env
          echo "AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }}" >> .env
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env
          echo "BUCKET_NAME=${{ secrets.BUCKET_NAME }}" >> .env
          echo "ROLE_ARN=${{ secrets.ROLE_ARN }}" >> .env

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: |
          python deploy.py  # Jalankan skrip Python untuk upload ke S3
